[package]
name = "realcrud"
version = "0.1.0"
edition = "2021"

[dependencies]
postgres = "0.19"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
bcrypt = "0.12"
regex = "1.7"
dotenv = "0.15"
time = "0.3"

[features]
default = []
